{% set name = "pss" %}
{% set version = "1.45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pss-{{ version }}.tar.gz
  sha256: 13b81a4a7a33a7d6c4de85b908911c48849050fbaab596aeeceac78eaf067149

build:
  entry_points:
    - pss = psslib.pss:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - psslib
  commands:
    - pip check
    - pss --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eliben/pss
  summary: Tool for grepping through source code
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
